<style>
 img {
    width  : 100%;
    height : auto;
}


</style>


<h3><?php echo $this->escapeHtml($product->name); ?></h3>


<div class="ui-grid-a">
  <div class="ui-block-a"  style="width:20%" >Description:</div>
  <div class="ui-block-b" ><?php echo $this->escapeHtml($product->description); ?></div>
</div>
<div class="ui-grid-a">
  <div class="ui-block-a"  style="width:20%" >Price:</div>
  <div class="ui-block-b"><?php echo $this->escapeHtml($product->price); ?></div>
</div>

<div class="ui-grid-a">
<img src="<?php echo $this->basePath(); ?>/../module/Webshop/data/uploads/<?php echo $product->filename; ?>"  />
</div>






<?php
$user_session = new Zend\Session\Container('webshop');
//echo "_role: ".$user_session->role;
?>
<?php if (!empty($user_session->role)): ?> 

    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array('controller' => 'Product', 'action' => 'shoppingCart')));
    $form->setAttribute('method', 'post');

    echo $this->form()->openTag($form);
    ?>
    <table class="table">

        <tr>
            <td> <?php echo $this->formLabel($form->get('qty')); ?> </td>
            <td> <?php
                echo $this->formElement($form->get('qty'));
                echo $this->formElementErrors($form->get('qty'));
                ?> 
            </td>
        </tr>
        <tr>
            <td> &nbsp;</td>
            <td><?php
                echo $this->formElement($form->get('submit'));
                echo $this->formElementErrors($form->get('submit'));
                ?> <?php echo $this->formElement($form->get('store_product_id'));
            ?>
            </td>
        </tr>		
    </table>

    <?php echo $this->form()->closeTag() ?>

<?php else: ?> 
<br><br>
You can login  <a class="ui-btn ui-btn-inline ui-icon-carat-r ui-btn-icon-left" href="<?php echo $this->url('webshop/user', array('action' => 'index'), array()); ?>">Here</a> for shopping.

<br>
If you haven't registered yet click just

<a class="ui-btn ui-btn-inline ui-icon-carat-r ui-btn-icon-left" href="<?php echo $this->url('webshop/register', array('action' => 'index'), array()); ?>">Here</a>.

<?php endif; ?> 

